export const REVIEWS_LOADING = 'REVIEWS_LOADING';
export const ADD_REVIEWS = 'ADD_REVIEWS';
export const REVIEWS_FAILED = 'REVIEWS_FAILED';
export const ADD_COMMENTS = 'ADD_COMMENTS';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';
export const LATEST_LOADING = 'LATEST_LOADING';
export const ADD_LATEST = 'ADD_LATEST';
export const PROMOS_LATEST = 'PROMOS_LATEST';
